tmp

diff --git a/shell-env b/shell-env
--- a/shell-env
+++ b/shell-env
@@ -1,4 +1,5 @@
 #!/bin/bash
+set -e
 
 # user level apps
 export LOCAL_PATH="${HOME}/local"
@@ -24,13 +25,18 @@ check_platform (){
     if [[ "$OSTYPE" == "linux"* ]]; then
         distro_id=`lsb_release -d`
 
-        if [[ "$distro_id" == *"Debian"* ]]; then
+        if [[ "$distro_id" == *"Debian"* ]] || [[ "$distro_id" == *"Ubuntu"* ]]; then
             export os_platform="debian"
-        elif [[ "$distro_id" == *"Ubuntu"* ]]; then
-            export os_platform="debian"
+            export AWK_EXEC="awk"
+            export SED_EXEC="sed"
+        else
+            echo "Unsupported Linux distro: $distro_id"
+            exit 1
         fi
     elif [[ "$OSTYPE" == "darwin"* ]]; then
         export os_platform="osx"
+        export AWK_EXEC="gawk"
+        export SED_EXEC="gsed"
     fi
 }
 
@@ -44,5 +50,41 @@ user_confirm (){
     echo
     if [[ $confirm_result != "y" ]] && [[ $confirm_result != "Y" ]]; then
         exit 1
+    fi
+}
+
+sync_content (){
+    source_file="$1"
+    target_file="$2"
+    start_marker="$3"
+    end_marker="$4"
+
+    [[ ! -f "$source_file" ]] && echo "Source file not found: $source_file" && exit 1
+    [[ ! -f "$target_file" ]] && echo "Target file not found: $target_file" && exit 1
+
+    cp $target_file "$target_file.bak"
+
+    if grep -q "$start_marker" "$target_file" && grep -q "$end_marker" "$target_file"; then
+        gawk "/^$start_marker$/,/^$end_marker$/ {
+            if (/^$start_marker$/) {
+                print;
+                while ((getline line < \"$source_file\") > 0) {
+                    print line
+                }
+                close(\"$source_file\")
+                next
+            }
+            if (/^$end_marker$/) {
+                print;
+                next
+            }
+            next
+        }
+        {print}"  "$target_file.bak" >"$target_file"
+    else
+        { echo;
+        echo "$start_marker";
+        cat "$source_file";
+        echo "$end_marker"; } >> "$target_file"
     fi
 }
